# Generated by Django 4.1.3 on 2022-11-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_cashier_admin_cashier_default_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='last_login',
        ),
    ]
