# Generated by Django 4.1.3 on 2022-11-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_remove_cashier_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashier',
            old_name='default_location',
            new_name='location',
        ),
    ]
