# Generated by Django 4.2.4 on 2023-08-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_cashier_add_stock_access_cashier_inquiry_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='last_receipt_no',
            field=models.IntegerField(default=1),
        ),
    ]
