# Generated by Django 4.2.4 on 2023-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_cashier_last_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='cash_balance',
            field=models.IntegerField(default=0),
        ),
    ]
