# Generated by Django 4.2.4 on 2023-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_cashier_cash_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='inquiry_ascending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashier',
            name='inquiry_signature',
            field=models.BooleanField(default=False),
        ),
    ]
