# Generated by Django 4.1.3 on 2022-11-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_cashier_name_remove_cashier_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cashier',
        ),
    ]
