# Generated by Django 4.1.3 on 2022-11-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_stock_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='inquiry_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='invoice_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_report_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_return_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_balance_access',
            field=models.BooleanField(default=True),
        ),
    ]
