# Generated by Django 4.1.3 on 2022-11-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_item_add_stock_access_item_inquiry_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='add_stock_access',
        ),
        migrations.RemoveField(
            model_name='item',
            name='inquiry_access',
        ),
        migrations.RemoveField(
            model_name='item',
            name='invoice_access',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_access',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sales_report_access',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sales_return_access',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock_balance_access',
        ),
    ]
