# Generated by Django 4.1.3 on 2022-11-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.publisher'),
        ),
    ]
