# Generated by Django 4.1.3 on 2022-11-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_inquiry_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
