# Generated by Django 4.2.4 on 2023-08-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_inquiry_discount_inquiry_subtotal_inquiry_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('content', models.TextField(max_length=50000)),
                ('timeIssued', models.DateTimeField()),
            ],
        ),
    ]
