# Generated by Django 4.2.4 on 2023-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='timeIssued',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
