# Generated by Django 4.2.4 on 2023-08-22 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_receipt_timeissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='timeIssued',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 36, 41, 990549, tzinfo=datetime.timezone.utc)),
        ),
    ]
