# Generated by Django 4.2.4 on 2023-08-22 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_receipt_timeissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='timeIssued',
            field=models.DateTimeField(default=datetime.date(2023, 8, 22)),
        ),
    ]
