# Generated by Django 4.2.4 on 2023-08-22 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_receipt_timeissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='timeIssued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
