# Generated by Django 4.2.4 on 2023-09-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_publisher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='tel',
        ),
    ]
